### ISSUE TITLE
Übersicht anpassen.

### ISSUE THREAD

**Issue by dergel** [FriendsOfREDAXO/ylicense#1]
Aus Tabelle und Übersicht eine Tabellenansicht bauen.. in der die Infos der Übersicht mit drin sind.
Tabelle sortierbar nach Lizenz

**Comment by chip75** [comment]
Filter eingebaut. Rest muss später gemacht werden.

<img width="890" alt="screenshot 2018-12-19 10 52 03" src="https://user-images.githubusercontent.com/1301303/50212767-24382c80-037c-11e9-9d5e-9d351378f604.png">
<img width="1180" alt="screenshot 2018-12-19 10 51 59" src="https://user-images.githubusercontent.com/1301303/50212769-24382c80-037c-11e9-8fd9-89a6c31b2e6d.png">

**Comment by AWqxKAWERbXo** [comment]
close?
