### ISSUE TITLE
Verschiedene Lizenzen auflisten

### ISSUE THREAD

**Issue by dergel** [FriendsOfREDAXO/ylicense#2]
in der Übersicht, vielleicht obendrüber die verschiedenen Lizenzen auflisten
z.B.

MIT (40)
GPL (2)
Beerlizenz (2)

am liebsten auch so, dass man auf Klick, genau diese Lizenzen markiert bekommt.

**Comment by chip75** [comment]
Siehe Filter in Tabelle
