### ISSUE TITLE
Auflisten der Komponenten oder AddOns ohne Lizenz

### ISSUE THREAD

**Issue by dergel** [FriendsOfREDAXO/ylicense#3]
so dass man sehen kann wo man eventuell noch etwas klären muss

**Comment by chip75** [comment]
erstmal nur für Addons eine grobe Übersicht.

**Comment by AWqxKAWERbXo** [comment]
scheint mit drin zu sein

![image](https://user-images.githubusercontent.com/3855487/194813252-be5a1972-f0d1-4120-8aec-38b9e1c1a651.png)
