### ISSUE TITLE
Recht vergeben

### ISSUE THREAD

**Issue by dergel** [FriendsOfREDAXO/ylicense#4]
so dass man das jemandem zuweisen kann.

**Comment by chip75** [comment]
ist doch bereits dabei. oder was meinst du genau?

**Comment by chip75** [comment]
<img width="873" alt="screenshot 2018-12-19 10 22 56" src="https://user-images.githubusercontent.com/1301303/50211110-141e4e00-0378-11e9-9179-ed584083653a.png">

**Comment by dergel** [comment]
oh .. gar nicht gesehen .. aber auch so, dass es gar nicht erst auftaucht .. admin rechte muss man nicht vergeben und das rechte auf oberste ebene ylicense wäre gut + Übersetzung, die hier in der Roll auftaucht

**Comment by AWqxKAWERbXo** [comment]
https://github.com/FriendsOfREDAXO/license/blob/9c6d45abd6154e25d60215b2dc375a83a813eebc/package.yml#L8

close?
