### ISSUE TITLE
Error bei ylincense

### ISSUE THREAD

**Issue by dergel** [FriendsOfREDAXO/ylicense#6]
<img width="1264" alt="bildschirmfoto 2018-12-18 um 14 06 11" src="https://user-images.githubusercontent.com/322951/50156082-1cba4a00-02ce-11e9-940e-171649ad8bd7.png">

ParseError thrown with message "syntax error, unexpected '?', expecting variable (T_VARIABLE)"

Stacktrace:
#15 ParseError in /var/www/pwcplus/releases/183/public/redaxo/src/addons/ylicense/vendor/symfony/finder/Comparator/NumberComparator.php:42
#14 rex_autoload:autoload in [internal]:0
#13 spl_autoload_call in /var/www/pwcplus/releases/183/public/redaxo/src/addons/ylicense/vendor/symfony/finder/Finder.php:123
#12 Symfony\Component\Finder\Finder:depth in /var/www/pwcplus/releases/183/public/redaxo/src/addons/ylicense/lib/LicenseCheck.php:30
#11 LicenseCheck:getReposInfo in /var/www/pwcplus/releases/183/public/redaxo/src/addons/ylicense/lib/LicenseCheck.php:19
#10 LicenseCheck:getReposFromPath in /var/www/pwcplus/releases/183/public/redaxo/src/addons/ylicense/pages/main.php:2
#9 include in /var/www/pwcplus/releases/183/public/redaxo/src/core/lib/packages/package.php:228
#8 rex_package:includeFile in /var/www/pwcplus/releases/183/public/redaxo/src/core/lib/be/controller.php:456
#7 rex_be_controller:includePath in /var/www/pwcplus/releases/183/public/redaxo/src/core/lib/be/controller.php:420
#6 rex_be_controller:includeCurrentPageSubPath in /var/www/pwcplus/releases/183/public/redaxo/src/addons/ylicense/pages/index.php:14
#5 include in /var/www/pwcplus/releases/183/public/redaxo/src/core/lib/packages/package.php:228
#4 rex_package:includeFile in /var/www/pwcplus/releases/183/public/redaxo/src/core/lib/be/controller.php:456
#3 rex_be_controller:includePath in /var/www/pwcplus/releases/183/public/redaxo/src/core/lib/be/controller.php:403
#2 rex_be_controller:includeCurrentPage in /var/www/pwcplus/releases/183/public/redaxo/src/core/backend.php:155
#1 require in /var/www/pwcplus/releases/183/public/redaxo/src/core/boot.php:136
#0 require in /var/www/pwcplus/releases/183/public/redaxo/index.php:9

**Comment by staabm** [comment]
`?string` erfordert php 7.1

**Comment by dergel** [comment]
ok .. muss dann in die package.yml

**Comment by staabm** [comment]
alernativ kann ein "älteres" symfony release verwendet werden (falls ihr compat für ältere php versionen braucht)

**Comment by chip75** [comment]
7.1 erstmal als Pflicht in package.yml a20173719e7f0204321952a929e0d848e1d62d42
