### ISSUE TITLE
Pages in der Addonverwaltung einhängen

### ISSUE THREAD

**Issue by staabm** [FriendsOfREDAXO/ylicense#7]
*Zur Diskussion:*

wäre es sinnvoll wenn sich die subpages dieses addons in die addonsverwaltung einhängen würden, statt einen eigenen hauptmenupunkt zu bilden?

Lizensen brauch man vermutlich oftmals im zusammenhang mit komponenten und neuen addons und nicht im täglichen handwerkszeug

Ich finde das man in redaxo nicht für jedes addon einen hauptmenu punkt brauch und man in vielen installationen bereits unzählige hat

**Comment by AWqxKAWERbXo** [comment]
Das geht ohne Anpassungen am Core nicht möglich, keine Navigation verfügbar. https://github.com/redaxo/redaxo/blob/main/redaxo/src/core/pages/packages.php
