### ISSUE TITLE
ParseError:** syntax error, unexpected '?', expecting variable (T_VARIABLE)

### ISSUE THREAD

**Issue by skerbis** [FriendsOfREDAXO/ylicense#9]
**ParseError:** syntax error, unexpected '?', expecting variable (T_VARIABLE)
**File:** redaxo/src/addons/ylicense/vendor/symfony/finder/Comparator/NumberComparator.php
**Line:** 42

<details>
<summary>Stacktrace</summary>

| Function                                     | File                                                        | Line     |
| -------------------------------------------- | ----------------------------------------------------------- | -------- |
| rex_autoload::autoload                       |                                                             |          |
| spl_autoload_call                            | redaxo/src/addons/ylicense/vendor/symfony/finder/Finder.php | 123      |
| Symfony\Component\Finder\Finder->depth       | redaxo/src/addons/ylicense/lib/LicenseCheck.php             | 30       |
| LicenseCheck::getReposInfo                   | redaxo/src/addons/ylicense/lib/LicenseCheck.php             | 19       |
| LicenseCheck::getReposFromPath               | redaxo/src/addons/ylicense/pages/main.php                   | 2        |
| include                                      | redaxo/src/core/lib/packages/package.php                    | 228      |
| rex_package->includeFile                     | redaxo/src/core/lib/be/controller.php                       | 466      |
| rex_be_controller::includePath               | redaxo/src/core/lib/be/controller.php                       | 430      |
| rex_be_controller::includeCurrentPageSubPath | redaxo/src/addons/ylicense/pages/index.php                  | 14       |
| include                                      | redaxo/src/core/lib/packages/package.php                    | 228      |
| rex_package->includeFile                     | redaxo/src/core/lib/be/controller.php                       | 466      |
| rex_be_controller::includePath               | redaxo/src/core/lib/be/controller.php                       | 413      |
| rex_be_controller::includeCurrentPage        | redaxo/src/core/backend.php                                 | 191      |
| require                                      | redaxo/src/core/boot.php                                    | 150      |
| require                                      | redaxo/index.php                                            | 9        |

</details>
<details>
<summary>System report (REDAXO 5.7.0-beta1#55c009b, PHP 7.0.33)</summary>

| REDAXO        |                     |
| ------------: | :------------------ |
|       Version | 5.7.0-beta1#55c009b |

| PHP           |            |
| ------------: | :--------- |
|       Version | 7.0.33     |
|       OPcache | yes        |
|        Xdebug | no         |

| Database      |                         |
| ------------: | :---------------------- |
|       Version | 5.5.62-0ubuntu0.14.04.1 |
| Character set | utf8 (utf8_general_ci)  |

| Server        |            |
| ------------: | :--------- |
|            OS | Linux      |
|          SAPI | cgi-fcgi   |
|     Webserver | Apache     |

| Request       |               |
| ------------: | :------------ |
|       Browser | Safari/12.0.2 |
|      Protocol | HTTP/1.0      |
|         HTTPS | yes           |

| Packages                |             |
| ----------------------: | :---------- |
|                 adminer | 1.4.0       |
|                  backup | 2.2.2       |
|                be_style | 2.5.0       |
|     be_style/customizer | 2.5.0       |
|         be_style/redaxo | 2.5.0       |
|                  bricky | 0.0.1       |
|                icecoder | 1.0.0-beta1 |
|                 install | 2.4.0       |
|             maintenance | 1.2.6       |
|                  mblock | 3.0.1       |
|           media_manager | 2.5.6       |
|               mediapool | 2.4.2       |
|                metainfo | 2.3.1       |
|                   mform | 5.2.4       |
|              mform/docs | 1.0         |
|               phpmailer | 2.5.0-dev   |
|                 project | dev         |
|               redactor2 | 3.5.0       |
|               structure | 2.6.1       |
|       structure/content | 2.6.1       |
|                ui_tools | 0.4.0       |
| ui_tools/custom_widgets | 1.0.0       |
|                uploader | 2.0.1       |
|                   users | 2.5.0       |
|                   video | 1.3.2       |
|                   yform | 3.0-beta3   |
|              yform/docs | 3.0-beta3   |
|             yform/email | 3.0-beta3   |
|           yform/manager | 3.0-beta3   |
|                ylicense | 0.9.0       |
|                yrewrite | 2.4         |
|             zip_install | 1.1         |

</details>

**Comment by staabm** [comment]
Php7.1 required

**Comment by staabm** [comment]
Duplicates https://github.com/yakamara/ylicense/issues/6

**Comment by skerbis** [comment]
Ok, dann sollte es sich aber nicht installieren lasse . Package anpassen?

**Comment by staabm** [comment]
Ist bereits passiert - nur noch nicht im installer
